# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comText', models.CharField(max_length=100)),
                ('comDate', models.DateField()),
                ('comPubName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.CharField(max_length=100)),
                ('pubDate', models.DateField()),
                ('publisherName', models.CharField(max_length=20)),
                ('numOfComments', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
